# Generated by Django 3.0.7 on 2020-07-29 06:55

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250)),
                ('summary', models.CharField(max_length=600)),
                ('detail', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to=portfolio.models.image_path)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.Skill')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
