# Generated by Django 3.0.7 on 2020-08-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200802_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='category',
            new_name='group',
        ),
    ]
