# Generated by Django 3.0.7 on 2020-08-02 15:52

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200802_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSourceProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to=portfolio.models.image_path)),
            ],
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ('-completed', 'name')},
        ),
        migrations.CreateModel(
            name='OpenSourceContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.URLField(blank=True)),
                ('contributed_on', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='portfolio.OpenSourceProject')),
            ],
            options={
                'ordering': ('-contributed_on', 'name'),
            },
        ),
    ]
