# Generated by Django 3.0.7 on 2020-08-04 08:28

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200802_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to=portfolio.models.image_path)),
            ],
        ),
    ]
