# Generated by Django 3.0.7 on 2020-08-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_codingprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificategroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='opensourceproject',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
